name: Publish package to Github Packages
on: 
  push:
  
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'    
          
    - name: Set up Maven
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        maven-version: '3.8.4'
        distribution: 'adopt'

    - name: Configure Maven settings.xml
      run: |
        mkdir -p $HOME/.m2
        echo "<settings xmlns=\"http://maven.apache.org/SETTINGS/1.0.0\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd\"><servers><server><id>github</id><username>${{ github.actor }}</username><password>${{ secrets.PKG4_TOKEN }}</password></server></servers></settings>" > $HOME/.m2/settings.xml
        
    - name: Publish package
      run: mvn --batch-mode deploy --settings $HOME/.m2/settings.xml
